const PRIMARY_HUE = 156;
const PRIMARY_SATURATION = 100;
const PRIMARY_LIGHTNESS = 31;

const SECONDARY_HUE = 221;
const SECONDARY_SATURATION = 44;
const SECONDARY_LIGHTNESS = 41;

module.exports = {
    PRIMARY_COLOR: 'hsl('+PRIMARY_HUE+','+PRIMARY_SATURATION+'%,'+PRIMARY_LIGHTNESS+'%)',
    PRIMARY_HUE : PRIMARY_HUE,
    PRIMARY_SATURATION: PRIMARY_SATURATION,
    PRIMARY_LIGHTNESS: PRIMARY_LIGHTNESS,
    SECONDARY_COLOR: 'hsl('+SECONDARY_HUE+','+SECONDARY_SATURATION+'%,'+SECONDARY_LIGHTNESS+'%)',
    SECONDARY_HUE : SECONDARY_HUE,
    SECONDARY_SATURATION: SECONDARY_SATURATION,
    SECONDARY_LIGHTNESS: SECONDARY_LIGHTNESS,

}

